import { useState } from 'react'
import { useMutation } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import { Building2, Sparkles } from 'lucide-react'
import { toast } from 'sonner'
import registerVisual from '../assets/visuals/auth-register.svg'
import { apiRequest, ensureCsrfCookie } from '../lib/api'
import type { AuthUser, RegisterPayload } from '../types/auth'

export function RegisterPage() {
  const [result, setResult] = useState('Create your tenant workspace and owner account.')
  const [form, setForm] = useState<RegisterPayload>({
    tenant_name: '',
    owner_name: '',
    owner_email: '',
    password: '',
    password_confirmation: '',
  })

  const mutation = useMutation({
    mutationFn: async (): Promise<AuthUser> => {
      const loadingToast = toast.loading('Creating your workspace...')

      try {
        await ensureCsrfCookie()
        const data = await apiRequest<AuthUser>('/api/v1/auth/register-tenant', {
          method: 'POST',
          body: JSON.stringify(form),
        })
        toast.success('Workspace created successfully', { id: loadingToast })

        return data
      } catch (error) {
        toast.error((error as Error).message, { id: loadingToast })
        throw error
      }
    },
    onSuccess: (data) => {
      setResult(
        `Workspace created. Your tenant slug is ${data.tenant_slug}. Use this slug when logging in.`,
      )
    },
    onError: (error) => setResult((error as Error).message),
  })

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    if (
      !form.tenant_name.trim() ||
      !form.owner_name.trim() ||
      !form.owner_email.trim() ||
      !form.password.trim() ||
      !form.password_confirmation.trim()
    ) {
      toast.error('Please complete all required fields.')
      return
    }

    if (form.password.length < 8) {
      toast.error('Password must be at least 8 characters.')
      return
    }

    if (form.password !== form.password_confirmation) {
      toast.error('Password and confirmation do not match.')
      return
    }

    mutation.mutate()
  }

  return (
    <section className="auth-premium-layout">
      <aside className="auth-showcase">
        <img src={registerVisual} alt="Workspace registration visual" className="auth-image" />
        <p className="eyebrow">Workspace Onboarding</p>
        <h1>Launch your rental SaaS workspace</h1>
        <p>
          Create your tenant account, assign owner privileges, and start managing your portfolio
          with secure multi-tenant architecture.
        </p>
        <div className="auth-points">
          <p>
            <Building2 size={16} /> Provision tenant and owner in one step
          </p>
          <p>
            <Sparkles size={16} /> Production-ready auth and role scaffolding
          </p>
        </div>
      </aside>

      <form className="auth-premium-form" onSubmit={handleSubmit}>
        <h2>Create Workspace</h2>
        <p className="muted">Tenant slug will be auto-generated by the system.</p>

        <label>
          <span>Business Name</span>
          <input
            value={form.tenant_name}
            onChange={(event) => setForm((prev) => ({ ...prev, tenant_name: event.target.value }))}
            placeholder="Sunrise Boarding House"
          />
        </label>
        <label>
          <span>Owner Name</span>
          <input
            value={form.owner_name}
            onChange={(event) => setForm((prev) => ({ ...prev, owner_name: event.target.value }))}
            placeholder="Alex Rivera"
          />
        </label>
        <label>
          <span>Owner Email</span>
          <input
            type="email"
            value={form.owner_email}
            onChange={(event) => setForm((prev) => ({ ...prev, owner_email: event.target.value }))}
            placeholder="owner@sunrise.com"
          />
        </label>
        <label>
          <span>Password</span>
          <input
            type="password"
            value={form.password}
            onChange={(event) => setForm((prev) => ({ ...prev, password: event.target.value }))}
            placeholder="Minimum 8 characters"
          />
        </label>
        <label>
          <span>Confirm Password</span>
          <input
            type="password"
            value={form.password_confirmation}
            onChange={(event) =>
              setForm((prev) => ({ ...prev, password_confirmation: event.target.value }))
            }
            placeholder="Repeat password"
          />
        </label>

        <button type="submit" className="btn btn-primary" disabled={mutation.isPending}>
          {mutation.isPending ? 'Creating...' : 'Create Workspace'}
        </button>

        {mutation.isPending && <p className="form-hint">Submitting registration...</p>}

        <p className="footnote">
          Already have an account? <Link to="/login">Login</Link>
        </p>
        <pre className="result-card">{result}</pre>
      </form>
    </section>
  )
}
